catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ProductDetailView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactsPageView,
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView, CategoryListView, CategoryDetailView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("categories/category/<int:pk>", cache_page(60)(CategoryDetailView.as_view()), name="category"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("product/<int:pk>", cache_page(60)(ProductDetailView.as_view()), name="product"),
    path("blog_list/", BlogListView.as_view(), name="blog_list"),
    path("blog_list/blog/<int:pk>", BlogDetailView.as_view(), name="blog"),
    path("blog_list/blog/create", BlogCreateView.as_view(), name="create"),
    path("blog_list/blog/update/<int:pk>", BlogUpdateView.as_view(), name="update"),
    path("blog_list/blog/delete/<int:pk>", BlogDeleteView.as_view(), name="delete"),
    path("product/create", ProductCreateView.as_view(), name="create_product"),
    path("product/update/<int:pk>", ProductUpdateView.as_view(), name="update_product"),
    path("product/delete/<int:pk>", ProductDeleteView.as_view(), name="delete_product"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import UserCreateView, email_verification, UserResetPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("register/", UserCreateView.as_view(), name='register'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path('password_reset/', UserResetPasswordView.as_view(), name='password_reset'),
]

catalog/models.py
from django.db import models

from users.models import User


# Create your models here.


class Category(models.Model):
    """Category
    Наименование
    Описание"""

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        blank=True,
        null=True,
        max_length=300,
        verbose_name="Описание категории",
        help_text="Введите описание категории",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    """Product:
    Наименование
    Описание
    Изображение (превью)
    Категория
    Цена за покупку
    Дата создания (записи в БД)
    Дата последнего изменения (записи в БД)"""

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        blank=True,
        null=True,
        max_length=300,
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
    )
    photo = models.ImageField(
        upload_to="media/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        max_length=100,
        verbose_name="Категория продукта",
        help_text="Введите категорию продукта",
        null=True,
        blank=True,
        related_name="products",
    )
    price = models.PositiveIntegerField(
        verbose_name="Стоимость продукта",
        help_text="Введите стоимость продукта",
    )
    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания (записи в БД)",
        help_text="Введите Дату создания",
    )
    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения (записи в БД)",
        help_text="Введите Дату последнего изменения",
    )

    owner = models.ForeignKey(User, verbose_name='Владелец', blank=True, null=True, on_delete=models.SET_NULL)
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')

    """   manufactured_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата производства",
        help_text="Введите Дату производства",
    )
"""

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "price"]

        permissions = [
            (
                'set_published',
                'Can publish posts'
            ),
            (
                'change_description',
                'Can change description'
            ),
            (
                'change_category',
                'Can change category'
            )
        ]


"""Свяжите продукт и категорию, используя связь между таблицами «Один ко многим».
У одной категории может быть много продуктов, но у одного продукта может быть только одна категория.
Воспользуйтесь специальным полем модели — ForeignKey()."""


class Version(models.Model):
    product = models.ForeignKey(
        Product, null=True, verbose_name="Продукт", on_delete=models.SET_NULL
    )
    version_number = models.PositiveIntegerField(verbose_name="Номер версии")
    version_name = models.CharField(max_length=50, verbose_name="Название версии")
    version_is_active = models.BooleanField(
        default=True, verbose_name="Активная версия?"
    )

    def __str__(self):
        # Строковое отображение объекта
        return f"Версия {self.version_number} продукта {self.product} {'активна' if self.version_is_active else 'неактивна'}"

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"


class Blog(models.Model):
    """заголовок;
    slug (реализовать через CharField);
    содержимое;
    превью (изображение);
    дата создания;
    признак публикации;
    количество просмотров."""

    title = models.CharField(
        max_length=100,
        verbose_name="Заголовок статьи",
        help_text="Введите заголовок статьи",
    )
    slug = models.CharField(
        max_length=200,
        verbose_name="slug",
        blank=True,
        null=True,
    )
    content = models.TextField(
        blank=True,
        null=True,
        verbose_name="Содержимое статьи",
        help_text="Введите текст статьи",
    )
    preview = models.ImageField(
        upload_to="media/photo",
        blank=True,
        null=True,
        verbose_name="Превью",
        help_text="Загрузите изображение",
    )
    created_at = models.DateField(
        auto_created=True,
        blank=True,
        null=True,
        verbose_name="Дата создания (записи в БД)",
        help_text="Введите Дату создания",
    )
    is_publication = models.BooleanField(default=True, verbose_name="опубликовано")
    views_count = models.PositiveIntegerField(default=0, verbose_name="просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["title"]

catalog/views.py
import django.core.exceptions
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from catalog.models import Product, Blog, Category
from catalog.models import Product, Blog, Version
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from django.views.generic.base import TemplateView
from django.forms import inlineformset_factory
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from pytils.translit import slugify

from catalog.services import get_categories_from_cache, get_products_from_cache

"""def home(request):
    context = {"product_list": Product.objects.all()}
    return render(request, "product_list.html", context=context)"""


# Перевели имеющиеся контроллеры с FBV на CBV
class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    login_url = "/users/login/"

    def get_queryset(self):
        return get_products_from_cache()

"""def contacts(request):
    if request.method == "POST":
        # в переменной request хранится информация о методе, который отправлял пользователь
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")

        # а также передается информация, которую заполнил пользователь
        print(name, phone, message)
    return render(request, "contacts.html")
"""


# Перевели имеющиеся контроллеры с FBV на CBV
class ContactsPageView(TemplateView):
    template_name = "catalog/contacts.html"


# FBV
"""def product(request, pk):
    try:
        context = {"product": Product.objects.get(pk=pk)}
        return render(request, "product_detail.html", context=context)
    except django.core.exceptions.ObjectDoesNotExist:
        return render(request, "404.html")
"""


# Перевели имеющиеся контроллеры с FBV на CBV
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = "/users/login/"

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")
    login_url = "/users/login/"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        ProductFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            user = self.request.user
            self.object.owner = user
            self.object.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:

            return self.render_to_response(
                self.get_context_data(form=form, formset=formset)
            )

    """def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)"""


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")
    login_url = "/users/login/"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        ProductFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]

        if form.is_valid() and formset.is_valid():
            self.object = form.save()

            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:

            return self.render_to_response(
                self.get_context_data(form=form, formset=formset)
            )

    """def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.save()

        return super().form_valid(form)"""

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.set_published") and user.has_perm("catalog.change_description") and user.has_perm("catalog.change_category"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product  # Модель
    success_url = reverse_lazy(
        "catalog:home"
    )  # Адрес для перенаправления после успешного удаления
    login_url = "/users/login/"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.set_published") and user.has_perm("catalog.change_description") and user.has_perm("catalog.change_category"):
            return ProductModeratorForm
        raise PermissionDenied

class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    login_url = "/users/login/"

    def get_queryset(self):
        return get_categories_from_cache()

class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    login_url = "/users/login/"

class BlogListView(ListView):
    model = Blog

    """get_queryset выводит в список статей только те, которые имеют положительный признак публикации"""

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_publication=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    """При открытии отдельной статьи get_object увеличивает счетчик просмотров"""

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog  # Модель
    fields = (
        "title",
        "content",
        "preview",
    )  # Поля для заполнения при создании
    success_url = reverse_lazy(
        "catalog:blog_list"
    )  # Адрес для перенаправления после успешного создания

    """form_valid при создании динамически формирует slug name для заголовка"""

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog  # Модель
    fields = (
        "title",
        "content",
        "preview",
    )  # Поля для редактирования
    #    success_url = reverse_lazy('catalog:blog_list') # Адрес для перенаправления после успешного редактирования

    """form_valid при создании динамически формирует slug name для заголовка"""

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    """После успешного редактирования записи get_success_url перенаправляет пользователя на просмотр этой статьи"""

    def get_success_url(self):
        return reverse("catalog:blog", args=[self.kwargs.get("pk")])



class BlogDeleteView(DeleteView):
    model = Blog  # Модель
    success_url = reverse_lazy(
        "catalog:blog_list"
    )  # Адрес для перенаправления после успешного удаления

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Удалить запись
    </h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Подтвердить удаление "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-primary">Да</button>
                        <a href="/blog_list" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статья {{ object.title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <img class="col-9" src="{{ object.preview | media_filter }}">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Заголовок</td>
                            <td>{{ object.title }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Slug</td>
                            <td>{{ object.slug }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Содержание</td>
                            <td>{{ object.content }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата создания</td>
                            <td>{{ object.created_at }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Является публикацией</td>
                            <td>{{ object.is_publication }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

catalog/templates/catalog/blog_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Березка</h1>
    <p class="lead">Магазин Березка - все самое свежее!</p>
    <a class="p-2 btn btn-outline-primary" href="/blog_list/blog/create">Создать статью</a>
</div>

<div class="container">
    <div class="row text-center">
        {% for blog in blog_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <a href="blog/{{ blog.pk }}"><h4 class="my-0 font-weight-normal">{{ blog.title }}</h4></a>
                </div>

                <div class="card-body">
                    <img class="col-9" src="{{ blog.preview | media_filter }}">
                    <h1 class="card-title pricing-card-title">{{ blog.preview }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{% limit_text_100 blog.content %}</li>
                    <a class="p-2 btn btn-outline-primary" href="/blog_list/blog/update/{{ blog.pk }}">Обновить статью</a>
                    <a class="p-2 btn btn-outline-primary" href="/blog_list/blog/delete/{{ blog.pk }}">Удалить статью</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категория {{ object }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Название</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Описание</td>
                            <td>{{ object.description }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Березка</h1>
    <p class="lead">Магазин Березка - все самое свежее!</p>
    <a class="p-2 btn btn-outline-primary" href="product/create">Добавить продукт</a>
</div>

<div class="container">
    <div class="row text-center">
        {% for category in category_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <a href="category/{{ category.pk }}"><h4 class="my-0 font-weight-normal">{{ category.name }}</h4></a>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{% limit_text_100 category.description %}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Удаление продукта
    </h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Подтвердить удаление "{{ object.name }}" ?</p>
                        <button type="submit" class="btn btn-primary">Да</button>
                        <a href="/" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Березка</h1>
    <p class="lead">Магазин Березка - все самое свежее!</p>
    <a class="p-2 btn btn-outline-primary" href="product/create">Добавить продукт</a>
</div>

<div class="container">
    <div class="row text-center">
        {% for product in product_list %}
        {% if product.is_published or perms.catalog.set_published %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <a href="product/{{ product.pk }}"><h4 class="my-0 font-weight-normal {% if not product.is_published %} bg-danger {% endif %}">{{ product.name }}</h4></a>
                </div>

                <div class="card-body">
                    <img class="col-9" src="{{ product.photo | media_filter }}">
                    <h1 class="card-title pricing-card-title">{{ product.price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{% limit_text_100 product.description %}</li>
                        {% for version in product.version_set.all %}
                        {% if version.product == product and version.version_is_active == True %}
                            <li>Версия: {{ version.version_number }}</li>
                        {% endif %}
                    {% endfor %}

                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    {% if perms.catalog.set_published and perms.catalog.change_category and perms.catalog.change_description or user == product.owner %}
                    <a class="p-2 btn btn-outline-primary" href="product/update/{{ product.pk }}">Обновить продукт</a>
                    <a class="p-2 btn btn-outline-primary" href="product/delete/{{ product.pk }}">Удалить продукт</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}